src/LicensingService/Controllers/UserInfoController.cs
using Licensing.Web.DAL;
using Licensing.Web.Models;
using LicensingService.Controllers;
using SoftActivate.Licensing;
using System;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Data.Entity;

namespace LicensingService
{
    public class UserInfoController : LicensingServiceController
    {
        private LicensingServiceDbContext db = new LicensingServiceDbContext();

        // GET api/<controller>/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {

        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {

        }
    }
}

src/LicensingService/Areas/ControlPanel/Views/Shared/_ActivationListPartial.cshtml
@model PagedList.IPagedList<Licensing.Web.Models.Activation>

<div class="dbtablewrap">
    <table class="dbtable">
        <tr>
            <th>
                @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Version", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Company", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("License Key", "Index", new { sortOrder = ViewBag.LicenseKeySortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Hardware Id", "Index", new { sortOrder = ViewBag.CustomerNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Activation Key", "Index", new { sortOrder = ViewBag.CustomerNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.CustomerUserNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("LoginDate", "Index", new { sortOrder = ViewBag.CustomerUserNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HardwareId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivationKey)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoginDate)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Activation", new { id = item.Id }, null)

                    @if (User.IsInRole("Administrators"))
                    {
                        @:|
                        @Html.ActionLink("Edit", "Edit", "Activation", new { id = item.Id }, null)
                        @:|
                        using (Html.BeginForm("Delete/" + item.Id, "Activation", FormMethod.Post, new { id = "deleteForm_" + item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to delete this activation record ?')) {document.getElementById('deleteForm_@item.Id').submit()}">Delete</a>
                        }
                        @:|
                        using (Html.BeginForm("InActivation/" + item.Id, "Activation", FormMethod.Post, new { id = "InActivationForm_" + item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to Inactivation record ?')) {document.getElementById('InActivationForm_@item.Id').submit()}">InActivation</a>
                        }
                        @:|
                        using (Html.BeginForm("CheckActivation/" + item.Id, "Activation", FormMethod.Post, new { id = "CheckActivationForm_" + item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to Checkactivation record ?')) {document.getElementById('CheckActivationForm_@item.Id').submit()}">Check</a>
                        }
                    }
                </td>
            </tr>
        }

    </table>
</div>

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    &nbsp;
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
    }
    else
    {
        @:<<
        @Html.Raw("&nbsp;");
        @:< Prev
    }
    &nbsp;
    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
    }
    else
    {
        @:Next >
        @Html.Raw("&nbsp;")
        @:>>
    }
</div>

src/LicensingService/Areas/ControlPanel/Views/Shared/_InActivationListPartial.cshtml
@model PagedList.IPagedList<Licensing.Web.Models.InActivation>

<div class="dbtablewrap">
    <table class="dbtable">
        <tr>
            <th>
                @Html.ActionLink("InActivation Date", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Version", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Company", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("License Key", "Index", new { sortOrder = ViewBag.LicenseKeySortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Hardware Id", "Index", new { sortOrder = ViewBag.CustomerNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Activation Key", "Index", new { sortOrder = ViewBag.CustomerNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.CustomerNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.InActivationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HardwareId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivationKey)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CheckAdmin)
                    @Html.ActionLink("Details", "Details", "InActivation", new { id = item.Id }, null)

                    @if (User.IsInRole("Administrators"))
                    {
                        @:|
                        @Html.ActionLink("Edit", "Edit", "InActivation", new { id = item.Id }, null)
                        @:|
                        using (Html.BeginForm("Delete/" + item.Id, "InActivation", FormMethod.Post, new { id = "deleteForm_" + item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to delete this InActivation record ?')) {document.getElementById('deleteForm_@item.Id').submit()}">Delete</a>
                        }
                    }
                </td>
            </tr>
        }

    </table>
</div>

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    &nbsp;
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
    }
    else
    {
        @:<<
        @Html.Raw("&nbsp;");
        @:< Prev
    }
    &nbsp;
    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"], GlobalList = ViewData["GlobalList"] })
    }
    else
    {
        @:Next >
        @Html.Raw("&nbsp;")
        @:>>
    }
</div>

src/LicensingService/Areas/ControlPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - SoftActivate Licensing Control Panel</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
    </head>
    <body>
        <div id="header">
            <div class="center" id="center-header">
                <div id="logoOuter">
                    <div id="logoInner">
                        @Html.ActionLink("SoftActivate", "Index", "Home")
                        <span style="font-size: 1em; font-weight: bold">Licensing Control Panel</span>
                    </div>
                </div>
                <div id="usernav">
                    @Html.Partial("_LoginPartial")
                </div>
                <div id="nav">
                    <ul class="navlist">
                        <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                            <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                            <li>@Html.ActionLink("Products", "Index", "Product")</li>
                            <li>@Html.ActionLink("License Keys", "Index", "LicenseKey")</li>
                            <li>@Html.ActionLink("Activations", "Index", "Activation")</li>
                        <li>@Html.ActionLink("TrialActivations", "Index", "TrialActivation")</li>
                        <li>@Html.ActionLink("UserNames", "Index", "UserName")</li>
                        <li>@Html.ActionLink("UserInfos", "Index", "UserInfo")</li>
                        <li>@Html.ActionLink("InActivations", "Index", "InActivation")</li>
                        <li>@Html.ActionLink("Event Log", "Index", "EventLog")</li>
                        <li>@Html.ActionLink("Download", "Download", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="content">
            <div id="center-content">
                @RenderSection("featured", required: false)
                @RenderBody()
            </div>
        </div>
        <div id="footer">
            <p>&copy; @DateTime.Now.Year - SoftActivate</p>
        </div>
        @RenderSection("scripts", required: false)
    </body>
</html>

src/LicensingService/Areas/ControlPanel/Views/Shared/_OrderListPartial.cshtml
@model PagedList.IPagedList<Licensing.Web.Models.OrderItem>

<div class="dbtablewrap">
    <table class="dbtable">
        <tr>
            <th>
                @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product", "Index", new { sortOrder = ViewBag.ProductNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Quantity", "Index", new { sortOrder = ViewBag.QuantitySortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Version", "Index", new { sortOrder = ViewBag.CountrySortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                업체명
            </th>
            <th>
                담당자
            </th>
            <th>
                @Html.ActionLink("Company", "Index", new { sortOrder = ViewBag.CompanyNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>&nbsp;</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.OrderTotal)&nbsp;@Html.DisplayFor(modelItem => item.Order.Currency)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.Company)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Order", new { id = item.Id }, null)
                                       
                    @if (User.IsInRole("Administrators"))
                    {
                        @:|
                        @Html.ActionLink("Edit", "Edit", "Order", new { id = item.Id }, null) 
                        @:|
                        using (Html.BeginForm("Delete/" + item.OrderId, "Order", FormMethod.Post, new { id = "deleteForm_" + item.OrderId }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to delete this order ?')) {document.getElementById('deleteForm_@item.OrderId').submit()}">Delete</a>
                        }
                    }
                </td>
            </tr>
        }

    </table>
</div>

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    &nbsp;
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", null, new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl="orderlist" })
        @Html.Raw("&nbsp;");
        @Html.ActionLink("< Prev", null, new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl="orderlist"  })
    }
    else
    {
        @:<<
        @Html.Raw("&nbsp;");
        @:< Prev
    }
    &nbsp;
    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", null, new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl="orderlist" })
        @Html.Raw("&nbsp;");
        @Html.ActionLink(">>", null, new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl="orderlist" })
    }
    else
    {
        @:Next >
        @Html.Raw("&nbsp;")
        @:>>
    }
</div>

src/LicensingService/Areas/ControlPanel/Views/Shared/_SearchBoxPartial.cshtml
<div style="margin-top: 10px">
    <input id="search_query" name="search_query" type="text" />&nbsp;<button onclick="window.location='@Url.Action("Index", "Search")' + '?q=' + document.getElementById('search_query').value">Search</button>
</div>

src/LicensingService/Areas/ControlPanel/Views/Shared/_UserInfoListPartial.cshtml
@model PagedList.IPagedList<Licensing.Web.Models.UserInfo>

<div class="dbtablewrap">
    <table class="dbtable">
        <tr>
            <th>
                @Html.ActionLink("Edit Date", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Product", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Version", "Index", new { sortOrder = ViewBag.ProductSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Company", "Index", new { sortOrder = ViewBag.DateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("License Key", "Index", new { sortOrder = ViewBag.LicenseKeySortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.UserNameSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("ActivationCnt", "Index", new { sortOrder = ViewBag.NameInfoSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("IsHold", "Index", new { sortOrder = ViewBag.IsHoldSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("HoldDate", "Index", new { sortOrder = ViewBag.HoldDateSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("HoldCnt", "Index", new { sortOrder = ViewBag.HoldCntSortParam, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Operate
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EditDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.OrderItem.Order.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseKey.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActivationCnt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsHold)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoldDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoldCnt)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "UserInfo", new { id = item.Id }, null)

                    @if (User.IsInRole("Administrators"))
                    {
                        @:|
                        @Html.ActionLink("Edit", "Edit", "UserInfo", new { id = item.Id }, null)
                        @:|
                        using (Html.BeginForm("Delete/" + item.Id, "UserInfo", FormMethod.Post, new { id = "deleteForm_" + item.Id }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:if (confirm('Are you sure you want to delete this UserName record ?')) {document.getElementById('deleteForm_@item.Id').submit()}">Delete</a>
                        }
                    }
                </td>
            </tr>
        }

    </table>
</div>

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    &nbsp;
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"] })
    }
    else
    {
        @:<<
        @Html.Raw("&nbsp;");
        @:< Prev
    }
    &nbsp;
    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"] })
        @Html.Raw("&nbsp;");
        @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, selectedProduct = ViewData["selectedProduct"], startDate = ViewData["startDate"], endDate = ViewData["endDate"], pagedctl = "activationlist", CompanyName = ViewData["companyName"], LicenseKey = ViewData["licenseKey"], HardwareID = ViewData["hardwareID"] })
    }
    else
    {
        @:Next >
        @Html.Raw("&nbsp;")
        @:>>
    }
</div>