src/LicensingService/Areas/ControlPanel/Controllers/EventLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Licensing.Web.Models;
using Licensing.Web.DAL;
using PagedList;

namespace Licensing.ControlPanel.Controllers
{
    public class EventLogController : ControlPanelController
    {
        private LicensingServiceDbContext db = new LicensingServiceDbContext();

        //
        // GET: /ControlPanel/EventLog/

        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            return View(db.EventLog.OrderByDescending(item => item.Date).ToPagedList(pageNumber, 20));
        }

        //
        // GET: /ControlPanel/EventLog/Details/5

        public ActionResult Details(int id = 0)
        {
            Event e = db.EventLog.Find(id);
            if (e == null)
            {
                return HttpNotFound();
            }
            return View(e);
        }

        //
        // GET: /ControlPanel/EventLog/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ControlPanel/EventLog/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event e)
        {
            if (ModelState.IsValid)
            {
                db.EventLog.Add(e);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(e);
        }

        //
        // GET: /ControlPanel/EventLog/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Event e = db.EventLog.Find(id);
            if (e == null)
            {
                return HttpNotFound();
            }
            return View(e);
        }

        //
        // POST: /ControlPanel/EventLog/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event e)
        {
            if (ModelState.IsValid)
            {
                db.Entry(e).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(e);
        }

        //
        // GET: /ControlPanel/EventLog/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Event e = db.EventLog.Find(id);
            if (e == null)
            {
                return HttpNotFound();
            }
            return View(e);
        }

        //
        // POST: /ControlPanel/EventLog/Delete

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Administrators")]
        public ActionResult DeleteConfirmed()
        {
            //db.Database.ExecuteSqlCommand("TRUNCATE TABLE EventLog");
            db.Database.ExecuteSqlCommand("delete from EventLog");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/LicensingService/Areas/ControlPanel/Views/EventLog/Details.cshtml
@model Licensing.Web.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Event Details</h2>

<fieldset>
    <legend>Event Details</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
          @{
            switch (Model.Type)
            {
                case 0:
                    <text><span style="color: blue">Information</span></text>
                    break;
                
                case 1:
                    <text><span style="color: yellow">Warning</span></text>
                    break;
                
                case 2:
                    <text><span style="color: red">Error</span></text>
                    break;
            
                default:
                    <text>Unknown</text>
                    break;
            }  
        }
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Subject)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Subject)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Location)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Location)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Message)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Message)
    </div>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Url)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Url)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UrlParams)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UrlParams)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IPAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IPAddress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

src/LicensingService/Areas/ControlPanel/Views/EventLog/Index.cshtml
@model PagedList.IPagedList<Licensing.Web.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Event Log</h2>

@if (User.IsInRole("Administrators"))
{
    <p>
        @using (Html.BeginForm("Delete", "EventLog", FormMethod.Post, new { id = "deleteForm" })) {
            @Html.AntiForgeryToken()
            <a href="javascript:if (confirm('Are you sure you want to clear the event log ?')) {document.getElementById('deleteForm').submit()}">Clear Event Log</a>
        }
    </p>
}

<div class="dbtablewrap">
    <table class="dbtable">
        <tr>
            <th>
                Date
            </th>
            <th>
                Type
            </th>
            <th>
                Subject
            </th>
            <th>
                IP Address
            </th>
            <th>
                Location
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Date.ToString("G")
            </td>
            <td style="font-weight: bold">
                @{
                    switch (item.Type)
                    {
                        case 0:
                            <text><span style="color: blue">I</span></text>
                            break;
                
                        case 1:
                            <text><span style="color: yellow">W</span></text>
                            break;
                
                        case 2:
                            <text><span style="color: red">E</span></text>
                            break;
            
                        default:
                            <text>?</text>
                            break;
                    }  
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IPAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Id })
            </td>
        </tr>
    }

    </table>
</div>

<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount
    &nbsp;
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
        @Html.Raw("&nbsp;");
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
    }
    else
    {
        @:<<
        @Html.Raw("&nbsp;");
        @:< Prev
    }
    &nbsp;
    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
        @Html.Raw("&nbsp;");
        @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
    }
    else
    {
        @:Next >
        @Html.Raw("&nbsp;")
        @:>>
    }
</div>